# Generated by Django 6.0.4 on 2026-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_tenant_alter_customer_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(default='🍽️'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='emoji',
            field=models.TextField(default='🍽️'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.TextField(default='🍔'),
        ),
    ]
