# Generated by Django 6.0.4 on 2026-06-25 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergens_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Media'), ('hard', 'Difícil')], default='easy', max_length=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('draft', 'Borrador'), ('archived', 'Archivada')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='variations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inventoryitem'),
        ),
    ]
