# Generated by Django 6.0.4 on 2026-06-25 18:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recipe_full_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='features',
            field=models.JSONField(default=api.models._default_features),
        ),
        migrations.AddField(
            model_name='tenant',
            name='locations',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
