# Generated by Django 5.1.5 on 2026-07-02 19:27
# Editado a mano: agrega el campo slug SIN unicidad todavía. El backfill de
# datos y la restricción única se hacen en 0010 (ver ese archivo para el
# porqué de la separación).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_table_x_y_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, default=""),
            preserve_default=False,
        ),
    ]
