# Generated by Django 5.1.5 on 2026-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_table_x_y_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
