# Generated by Django 6.0.4 on 2026-07-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_purchase_subtotal_purchase_tax_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_sid', models.CharField(blank=True, max_length=60)),
                ('twilio_token', models.CharField(blank=True, max_length=60)),
                ('twilio_whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('glm_api_key', models.CharField(blank=True, max_length=120)),
                ('glm_model', models.CharField(default='glm-4.5-flash', max_length=40)),
                ('glm_base_url', models.URLField(default='https://open.bigmodel.cn/api/paas/v4')),
                ('enabled', models.BooleanField(default=False)),
                ('greeting', models.TextField(blank=True)),
                ('restaurant_name', models.CharField(blank=True, max_length=120)),
                ('menu_text', models.TextField(blank=True)),
                ('payment_info', models.TextField(blank=True)),
                ('business_info', models.TextField(blank=True)),
                ('menu_pdf', models.FileField(blank=True, null=True, upload_to='whatsapp/menus/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'verbose_name_plural': 'WhatsApp configs',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(default='Cliente', max_length=120)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('review', 'Por verificar'), ('verified', 'Verificado'), ('dispatched', 'Despachado'), ('rejected', 'Rechazado')], default='review', max_length=12)),
                ('receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('wa_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.whatsappcustomer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.whatsapporder')),
            ],
        ),
    ]
