# Generated by Django 6.0.4 on 2026-07-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_whatsapp_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_consumed',
            field=models.BooleanField(default=False),
        ),
    ]
