# Generated by Django 6.0.4 on 2026-07-23 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_stock_consumed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('edit', 'Edición'), ('add', 'Agregar'), ('remove', 'Eliminar'), ('status', 'Cambio de estado')], default='edit', max_length=12)),
                ('user', models.CharField(blank=True, max_length=80)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='api.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
