# Generated by Django 6.0.4 on 2026-07-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_orderchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='sale',
            name='observations',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='invoice_prefix',
            field=models.CharField(default='FV', max_length=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='invoice_seq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tenant',
            name='resolution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
