# Generated by Django 6.0.4 on 2026-07-27 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_product_restockable_creditnote_creditnoteline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='api.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_combos', to='api.product')),
            ],
            options={
                'unique_together': {('combo', 'product')},
            },
        ),
    ]
