# Generated by Django 6.0.4 on 2026-07-28 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_is_combo_comboitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('details', models.CharField(blank=True, max_length=300)),
                ('user', models.CharField(blank=True, max_length=80)),
                ('module', models.CharField(choices=[('ventas', 'Ventas'), ('inventario', 'Inventario'), ('menu', 'Menú'), ('proveedores', 'Proveedores'), ('reservaciones', 'Reservaciones'), ('mesas', 'Mesas'), ('empleados', 'Empleados'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('picked_up', 'Recogido'), ('on_the_way', 'En camino'), ('arrived', 'En sitio'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('avg_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tips', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('by_method', models.JSONField(default=dict)),
                ('by_waiter', models.JSONField(default=dict)),
                ('closed_by', models.CharField(blank=True, max_length=80)),
                ('records', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
