# Generated by Django 6.0.4 on 2026-07-29 01:59

from django.db import migrations, models

# Claves que antes se guardaban SIEMPRE en Tenant.features (el set completo por
# defecto). Al ser un dict completo, pisaba al plan y el plan nunca aplicaba.
LEGACY_KEYS = {
    "pos", "kitchen", "inventory", "recipes", "salon", "reservations",
    "crm", "suppliers", "employees", "reports", "website", "web_orders",
}


def drop_legacy_full_features(apps, schema_editor):
    """
    Vacía los features de los tenants que solo tienen el volcado histórico
    completo, para que pasen a regirse por su plan. Si un tenant tiene claves
    nuevas (qr, whatsapp, ai, max_users), se asume configuración deliberada
    del admin y se respeta.
    """
    Tenant = apps.get_model("api", "Tenant")
    for t in Tenant.objects.all():
        feats = t.features or {}
        if feats and set(feats).issubset(LEGACY_KEYS):
            t.features = {}
            t.save(update_fields=["features"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(drop_legacy_full_features, migrations.RunPython.noop),
    ]
