# Generated by Django 6.0.4 on 2026-07-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_tenant_features_override_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='purchase',
            name='received_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
