# Generated by Django 6.0.4 on 2026-08-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_purchase_due_date_purchase_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
