# Generated by Django 6.0.4 on 2026-08-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_product_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('y_start', models.FloatField(default=0)),
                ('height', models.FloatField(default=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ['y_start'],
            },
        ),
    ]
