# Generated by Django 6.0.4 on 2026-09-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_backfill_table_seated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_as_products', to='api.inventoryitem'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
