# Generated by Django 6.0.4 on 2026-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_product_cost_product_inventory_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('mini', 'Axis Mini'), ('starter', 'Básico'), ('growth', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('mini', 'Mini'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
