# Generated by Django 6.0.4 on 2026-09-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_link_products_by_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('simple', 'Simple'), ('compound', 'Requiere insumos')], default='simple', max_length=10),
        ),
    ]
