# Generated by Django 6.0.4 on 2026-09-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_seed_current_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needs_preparation',
            field=models.BooleanField(default=True),
        ),
    ]
