# Generated by Django 6.0.4 on 2026-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_product_needs_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='method',
            field=models.CharField(choices=[('card', 'Tarjeta'), ('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('pse', 'PSE')], default='cash', max_length=20),
        ),
    ]
