# Generated by Django 6.0.4 on 2026-09-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_sale_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
