# Generated by Django 6.0.4 on 2026-09-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_backfill_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='consumed_lines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sale',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='sales', to='api.order'),
        ),
    ]
