# Generated by Django 6.0.4 on 2026-09-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_sale_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='lines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sale',
            name='taxes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
